#
# file: .travis.yml
#
# author: Copyright (C) 2015 Kamil Szczygiel http://www.distortec.com http://www.freddiechopin.info
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# date: 2015-12-26
#

# use container-based infrastructure
sudo: false

# use minimal environment
language: generic

# bleeding-edge-toolchain
install:
    - wget http://www.freddiechopin.info/en/download/category/11-bleeding-edge-toolchain?download=139%3Ableeding-edge-toolchain-151225-64-bit-linux -O gcc-arm-none-eabi-5_3-151225-linux-x64.tar.xz
    - tar -xvf gcc-arm-none-eabi-5_3-151225-linux-x64.tar.xz
    - export PATH=$PWD/gcc-arm-none-eabi-5_3-151225/bin:$PATH

# configure and build selected configurations
script:
    - make configure CONFIG_PATH=32F429IDISCOVERY/test
    - make -j`nproc` VERBOSE=1
    - make distclean
    - make configure CONFIG_PATH=NUCLEO-F401RE/test
    - make -j`nproc` VERBOSE=1
    - make distclean
    - make configure CONFIG_PATH=STM32F4DISCOVERY/test
    - make -j`nproc` VERBOSE=1
    - make distclean
